Refatorando rotina para separação de lógica e responsabilidade
dedevpradev/faladev pull request #9
Opened 2024-07-16 17:46 UTC by mffonseca

## Descrição

Este pull request é uma refatoração da função de busca e atualização de eventos. As principais melhorias incluem a implementação de uma função dedicada para buscar eventos pelo link do Hangouts e a refatoração da função AddGuestToEvent para aumentar a clareza e facilitar futuras manutenções no código.

## Mudanças Realizadas

1. **Introdução da Função `findEventByHangoutLink`**:
   - Implementada para isolar a lógica de busca de eventos pelo link do Hangouts, facilitando futuras extensões ou modificações na maneira como os eventos são buscados.

2. **Refatoração da Lógica de Atualização de Eventos**:
   - A lógica de atualização de eventos após adicionar um convidado foi refatorada para maior clareza.

3. **Melhoria na Manipulação de Erros**:
   - As mensagens de erro agora utilizam `errors.Wrap` para incluir mais contexto e preservar a pilha de chamadas original, melhorando a capacidade de debug do sistema.

### Arquivos Modificados

- `internal/services/calendar.go`: Modificações nas funções de busca e atualização de eventos, além de melhorias na manipulação de erros.

### Mudanças Detalhadas

- **Busca de Evento por Link do Hangouts**:
   - A nova função `findEventByHangoutLink` busca eventos usando o link do Hangouts, tratando especificamente a ausência de eventos correspondentes com uma mensagem de erro clara.
  
- **Atualização e Manipulação de Eventos**:
   - Melhorada a função de atualização de eventos para incluir verificação de erros detalhada e registro de informações úteis para o log, facilitando a identificação de problemas e o acompanhamento de alterações nos eventos.

- **Melhorias na Tratativa de Erros**:
   - Utilização de `errors.Wrap` nas funções modificadas para garantir que a origem e a natureza dos erros sejam claramente identificadas e documentadas nos logs do sistema.

2024-07-16 23:06 UTC, tenlisboa approved these changes

2024-07-16 23:08 UTC, tenlisboa requested changes

2024-07-16 23:08 UTC, tenlisboa commented on internal/services/calendar.go
> +	"github.com/pkg/errors"
Teve um erro de build nesse package, provavelmente falta um `go get` nesse cara, já que o `go.mod` não está nas files changed.

2024-07-17 11:47 UTC, mffonseca commented on internal/services/calendar.go
> +	"github.com/pkg/errors"
@tenlisboa verdade. Atualizado.

2024-07-17 22:29 UTC, merged